#%RAML 1.0
---
title: DeeBeeTee
baseUri: http://southteam.xyz:5001/{version}
version: v1

/users:
  get:
    description: |
      Retrieve resource
    responses:
      200:
        description: |
          Succesfully retrieved resource
